apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchzone-fe
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchzone-fe
  template:
    metadata:
      labels:
        app: matchzone-fe
    spec:
      containers:
        - name: matchzone-fe
          image: acrfsaziaciks.azurecr.io/matchzone-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 150m
              memory: 150Mi
