apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
stringData:
  # DB URL: psql-fsa-ziaciks.postgres.database.azure.com
  #DB Username: "fsaadmin"
  #DB Password: "P@ssword12345!
  db_username: "fsaadmin"
  db_password: "P@ssword12345!"
  db_url: "psql-fsa-ziaciks.postgres.database.azure.com"

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  # Keycloak Username: admin
  # Keycloak Password: admin
  kc_username: YWRtaW4=
  kc_password: YWRtaW4=

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: infra
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
stringData:
  runner-registration-token: ""
  runner-token: "glrt-t1xqWUXbRR9W_XvGrkj39Gc6aQpvOjEKdDoyCnU6YQ8.01.170pod5nc"
